### ISSUE TITLE
CLI command list

### ISSUE THREAD

**Issue by shreyashankar** [loglabs/mltrace#157]
Currently we have:

- `recent`
- `history`
- `trace`

We would also like to include:

- `inspect COMPONENT_RUN_ID`
- `ls tags`
- `ls components`
- `ls components --tag=TAG`
- `ls components --owner=NAME`

We can use `get_components_for_owner` and `get_components_for_tag` to make the `ls` commands.

**Comment by shreyashankar** [comment]
Also include DB migration as a command

**Comment by shreyashankar** [comment]
On second thought, maybe `ls` is not the command to use. Maybe:

* `mltrace tags`
* `mltrace components`
* `mltrace components --tag=TAG`
* `mltrace components --owner=NAME`

Where the output of each of these commands is just a list of tags or components, one item per line.

**Comment by ariG23498** [comment]
I think this is a better CLI design. This aligns well with what we have now. I can work on this and put up a draft for the same. We can later discuss how this pans out and what needs to be changed.

**Comment by shreyashankar** [comment]
@aditim1359 is working on this

**Comment by aditim1359** [comment]
What exactly should "mltrace tags" be doing? Displaying all tags in use for all components?

**Comment by shreyashankar** [comment]
Yes -- a tag can be associated with many components. No point in filtering tags by component because we could just call `mltrace components --tag=TAG` for that
