### ISSUE TITLE
Isolated URL argument

### ISSUE THREAD

**Issue by ariG23498** [loglabs/mltrace#166]
https://github.com/loglabs/mltrace/blob/9c207e07a0ee0b94fa38170369268f3f1e28abed/mltrace/cli/cli.py#L191

I think this might have been left off while refactoring the code?

**Comment by shreyashankar** [comment]
My bad! Thank you for catching. Fixed in https://github.com/loglabs/mltrace/commit/409ee970489fd48d881adf89ccb37f3091f6b291
