### ISSUE TITLE
[Q] Different docker for CLI?

### ISSUE THREAD

**Issue by ariG23498** [loglabs/mltrace#168]
I was thinking whether we could have two different docker containers:
- For UI: Where we have the db, flask and react servers working altogether.
- For CLI: Where just the db server is all we need.

This also calls for a shared db IG, where the user is not constrained to any one of the docker.

**Comment by shreyashankar** [comment]
Yeah totally -- this is a good idea. Will keep it on the backlog :)

**Comment by shreyashankar** [comment]
@boyuan-deng will be working on this.

**Comment by shreyashankar** [comment]
Currently, the way to spin up `mltrace` is by spinning up all 3 services/containers -- the DB (backend), API, and UI (front end) -- through the [`docker-compose.yml`](https://github.com/loglabs/mltrace/blob/master/docker-compose.yml) file in the root directory. People may not want to use the UI at all times but still need to access the DB and API (ex: use CLI for querying), making it inefficient for them to also be running the UI container.

For this task, one must create a new `docker-compose.yml` file that spins up only the DB and API services. This new file can reside in the [cli directory](https://github.com/loglabs/mltrace/tree/master/mltrace/cli). Verify that the file works by 

* spinning up the new containers (running `docker-compose up` in the cli directory)
* making sure one cannot access localhost:8080 in their browser 
* making sure the DB works (run `python examples/tiny.py` from the root directory successfully)
* making sure the API works (use the CLI successfully, or run `mltrace recent` in your terminal)
