### ISSUE TITLE
DVC integration

### ISSUE THREAD

**Issue by jeannefukumaru** [loglabs/mltrace#176]
Hi, 

Happened to watch your talk at the Databricks Data and AI summit 🎉  . I enjoyed it a lot. 

You mentioned considering integrations with version control systems, which made me wonder whether you might consider integrating MLtrace with [DVC](https://dvc.org)? DVC is a system for managing versioning of models, datasets and also the pipelines that handle building models from data. What they offer seems to be closely related to what MLtrace does with tracing the lineage of data as it passes through different processing stages. 

A couple of thoughts I had: 

1. Include the dvc file hash / git tag associated with a file hash for a dataset/intermediate output in the info card of a component. We already have the git hash for the relevant git code commit and including the file hash for DVC might provide data versioning without the user having to manage input output versions through file naming. With the git tag, a user could backtrack to a previous project state by running `dvc checkout {git tag}`, thereby allowing them to inspect what may have changed (model / data / code) between an earlier experiment and the current one. 

2. Incorporate information from [`dvc status` ](https://dvc.org/doc/command-reference/status) into the staleness feature. The current staleness feature checks whether some time has passed since a component was run, or whether "dependencies have fresher runs that began before the component run started". `dvc status` would also say whether the dataset / intermediate output has been modified between runs, and hence whether or not the pipeline should be re-run. 

Design considerations: 
1. DVC has quite a few features. If we have a few we'd like to integrate into MLtrace, it might make sense to write a companion library similar to what Dagster has done with Great Expectations (dagster-ge) or with Pandas (dagster-pandas).
However, if we want to start with only one or two points of integration (eg. just the file hash), then we might consider adding a method to either the `ComponentRun` or `Component` classes that grabs the necessary information via the repo's .dvc file or the DVC Python API and displays that info in the UI / CLI

**Comment by shreyashankar** [comment]
This is a great idea! I think you can make a PR for each of your thoughts. Your design considerations make sense to me -- for a first pass (first thought), you can treat the dvc hash very similarly to the git hash (have a new attribute in `ComponentRun`. What do you think?

**Comment by jeannefukumaru** [comment]
Sounds good! I'm working on having the dvc has as a new attribute in `ComponentRun`. Should have a PR in a day or two 👍

**Comment by jeannefukumaru** [comment]
@shreyashankar  Looking into this further, we may not want to implement only a `get_dvc_hash()` function. Rather, each input and output into a `Component` or `ComponentRun` ideally should be checked against a `dvc.lock` to see whether it is tracked by DVC. (`dvc.lock` captures the versions of the dependencies and outputs of a pipeline run). If yes, then the corresponding file hash should be added as metadata to the input and output. 

To use an example `dvc.lock` and a `Component`:
```
schema: '2.0'
stages:
  clean:
    cmd: python 01_clean_data.py
    deps:
    - path: 01_clean_data.py
      md5: 63a0e6adf9ec6f916e1fb8a5f6ec73af
      size: 810
    - path: data/abalone.data
      md5: a769fd0119787cac09158fe08971e480
      size: 191873
    outs:
    - path: data/abalone.csv
      md5: 68821df28b91c28a287a67a6cb2a1bda
      size: 191968
```

```
@register(component_name="clean", input_vars=['input_filepath'], output_vars=['output_filepath'])
def clean(input_filepath: str, output_filepath: str) -> str:
    """
    process raw data by adding column names
    """
    raw = pd.read_csv(input_filepath, header=None)
    print('adding column names')
    raw.columns = ['sex','length','diameter','height','whole_weight','shucked_weight','viscera_weight','shell_weight','rings']
    print('saving data to csv')
    raw.to_csv(output_filepath, index=False)
```

`data/abalone.data` would be the input to the the `clean` `Component` and is tracked by DVC under `deps` so we might have `get_component_run_information` return `{"component_name": "clean", "inputs": [{"name": "data/abalone.data", "pointer_type": "UNKNOWN"}, "dvc_md5":"a769fd0119787cac09158fe08971e480"]`

Then in the case where a user wants to troubleshoot a version of a dataset that is giving problems, the dvc hash is there for reference. 

Modifying the IOPointer is a rather low-level solution though. There is a quicker fix where we can include a `git tag` as a `ComponentRun` attribute, and then include an example in the documentation where we show that a user can checkout a `dvc.lock` associated with the git tag of that particular `ComponentRun` and then dive deeper into the data by running `dvc checkout`. This is much more straightforward although there wouldn't be the cross-reference available between file hashes. 

What do you think? Sort of a tradeoff between effort and reward imho

**Comment by shreyashankar** [comment]
> There is a quicker fix where we can include a `git tag` as a ComponentRun attribute

I like this solution. Modifying the `IOPointer` is tedious because currently the `IOPointer` table's primary key is the filename.

**Comment by jeannefukumaru** [comment]
Okay we'll go with the `git tag` idea then :D
