### ISSUE TITLE
[Feature] Ability to "unflag all"

### ISSUE THREAD

**Issue by shreyashankar** [loglabs/mltrace#203]
It is probably tedious to go and unflag all flagged outputs. Add a command to unflag all.

**Comment by vishwanath1306** [comment]
The current `unflag` feature has `output_id` as a mandatory argument. If moving towards an `unflag all` option, it needs to be moved into `@click.argument` as an optional flag which can be checked. 

Modified part will look like:
```
@mltrace.command("unflag")
@click.option("--all")
@click.option("--output_id")
@click.option("--address", help="Database server address")
def unflag(output_id: str, address: str = ""):
    """
    Command to set the flag property of an output_id to false.
    """
    # Set address
    if address and len(address) > 0:
        set_address(address)
    unflag_output_id(output_id)
 ```
