### ISSUE TITLE
Add "notes" field to a component run

### ISSUE THREAD

**Issue by shreyashankar** [loglabs/mltrace#91]
This can be a place for knowledge sharing

**Comment by jeannefukumaru** [comment]
Hello, this component looks interesting. Would you have in mind what data structure you'd like for a "notes" field? For example, would it look like an additional `str` attribute to the `Component()` class 
```
class Component(Base):
    """Component abstraction."""

    def __init__(
        self, name: str, description: str, owner: str, tags: typing.List[str] = []
    ):
        """Components should have a name, description, and owner.
        Optionally they will have tags."""
        self._name = name
        self._description = description
        self._owner = owner
        self._tags = tags 
        **self.notes = notes**
```

Happy to see what I can do around this :)

**Comment by shreyashankar** [comment]
Thanks for the comment! On further thought, I think the "notes" field is actually more relevant to a `ComponentRun` than a `Component`. I imagine people want to make notes about a specific run, which might be one-off. 

I think your intuition of a string field for notes sounds about right. I think the most common way people might interact with this notes field is while querying the specific `ComponentRun` -- for example, in the UI, someone might add some notes. 

So we would need the following:

* notes (`str`) field in client data model
* notes (`Column(String)`) field in ORM data model
* db migration file (to add a column to the postgres table. see my WIP PR for an example of using alembic #161; we may have to merge this first)
* [editable text field](https://blueprintjs.com/docs/#core/components/editable-text) in `crinfocard.js` for user to view and edit notes

How does that sound?

**Comment by jeannefukumaru** [comment]
Sounds good ~ I've looked through the PR for Alembic, let's wait for the PR to merge then :)

**Comment by shreyashankar** [comment]
Sweet, i'll have it merged in the next 2 days or so :)

**Comment by shreyashankar** [comment]
Merged @jeannefukumaru !
