### ISSUE TITLE
Command wishlist

### ISSUE THREAD

**Issue by shreyashankar** [loglabs/mltrace#95]
`ls tags`
`ls components`
`ls components --owner [owner_name]`

**Comment by ariG23498** [comment]
Hey @shreyashankar 
Can we make these commands part of the CLI PR?

**Comment by shreyashankar** [comment]
Totally -- I think we can use `get_components_for_owner` and `get_components_for_tag` to make these CLI commands. I'd suggest making it a different PR though (to merge after the current one so things aren't cluttered). We also probably need CLI commands for every UI command to be consistent :)

**Comment by shreyashankar** [comment]
Closing this in favor of #157
